### ISSUE TITLE
This App Does Not Work

### ISSUE THREAD

**Issue by mongoose79** [aik099/custom.keylayout#2]
Hi,

I copied these files to both `Library` and `~Library`, but I don't see Letter Z keyboard in the list.
I use Apple M4 Pro, macOS: 15.3.1 (24D70)
Any ideas?

![Image](https://github.com/user-attachments/assets/938ea946-8dcb-44b2-a5b6-cfe3a90681a2)

**Comment by aik099** [comment]
Hi,

It wasn't showing for me as well (I suppose you did restart/relogin as recommended). Apparently doing restart/relogin isn't sufficient any more on the latest macOS version.

Try adding any of the built-in layout and then remove it. This triggered rescan of the `Library` and `~Library` folders and the `Russian - LetterZu` layout appeared out of nowhere. 😄

**Comment by mongoose79** [comment]
Could you specify exactly, what did you do to trigger rescan of the `Library` and `~Library` folders?
I added several languages and restarted my MacBook, but still I don't see `Russian - LetterZu` layout

**Comment by aik099** [comment]
Here is the video where I'm doing the same thing I've explained above:

https://github.com/user-attachments/assets/24df5d2e-0af7-4f7a-9eb5-4002b598a577

I hope you'll be able to repeat these steps.

P.S.
I'm not macOS Sequoia, but I think that an OS version different should cause any issues.

**Comment by mongoose79** [comment]
I tried again, but it doesn't work.
I saw that file sizes that I downloaded from GIT other that you displayed in your video.
Could you check it please?
Also, maybe you can add some guidelines to check it via terminal? For example, permissions etc.

![Image](https://github.com/user-attachments/assets/11b7a30f-86c4-482b-919e-76695c365851)

**Comment by aik099** [comment]
I've pushed my changes to the `master` branch. They're really minor:
* changed the icon to match macOS Monterey's monochrome icons (no flags anymore)
* corrected `.` key behavior on the Numeric Keyboard (was typing `,` previously)

Looking at your file sizes, I'm concluding that you've downloaded them incorrectly. I've checked that these sizes don't match to the GitHub repo file sizes. Please redownload them either by cloning a repo or by downloading in the raw format.

The `LetterZu.keylayout` file weights 41KB (plain text XML), and it can't grow to 1.3MB on its own.

**Comment by mongoose79** [comment]
It still doesn't work. I downloaded new files from GitHub and repeated all the steps including computer restart.
I attach the screenshots. Could you check please if I missed something?

![Image](https://github.com/user-attachments/assets/c1404d4e-4611-4c45-8553-27a5f4b2bfb8)

![Image](https://github.com/user-attachments/assets/9a371a9f-391c-4cf8-80bd-f4f454c2ab58)

![Image](https://github.com/user-attachments/assets/88ae53a0-a389-407a-9bcf-9c3993b9615a)

![Image](https://github.com/user-attachments/assets/b3dedffb-0324-4085-9b02-3a33f6b0bdef)

![Image](https://github.com/user-attachments/assets/532ae08e-7b0b-400f-806c-dc294956b369)

**Comment by aik099** [comment]
What about `Others` category, shown on your second screenshot? I have it right there as well:

![Image](https://github.com/user-attachments/assets/b0a45778-4ace-410c-89d7-68be1e142775)

**Comment by mongoose79** [comment]
Great, it works! I found "Letter Z" on "Others". Thank you!!! I suggest you to add this comment in your answer where you attached the video, because adding Russian as you did there doesn't work.
Could you please add mapping table and explain how to remap some letters please?
For example, on "Letter Z" "yu"="ю", while in your mapping you used "ю" as "ju"

**Comment by aik099** [comment]
> Great, it works! I found "Letter Z" on "Others". Thank you!!! I suggest you to add this comment in your answer where you attached the video, because adding Russian as you did there doesn't work.

I've updated installation instructions to cover the scenario you've suggested.

> Could you please add mapping table ...

You mean display all the used mappings in the README.md? Right now I explain some so people would get an idea, but not all of them.

You're welcome to send a PR with that change. Open the Ukelele.app and write down all the mappings you see. They're linked to dead keys.

> ... and explain how to remap some letters please?

I've used the [Ukelele.app](https://software.sil.org/ukelele/) app to create/edit the `*.keylayout` files. You can file detailed instructions on their website or the app itself.
